import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faInstagram,
  faFacebook,
  faSnapchat,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';
import {
  faHome,
  faSignInAlt,
  faSignOutAlt,
  faHistory,
  faBars,
  faUserPlus,
  faEnvelope,
  faHandshake,
  faPlus,
  faTimes,
  faSearch,
  faShoppingBag,
  faHashtag,
  faStar,
  faStoreAlt,
  faArrowRight,
  faUserAlt,
  faUtensils,
  faConciergeBell,
  faHamburger,
  faWineBottle,
  faSpinner,
  faTrashAlt,
  faShoppingCart,
  faCreditCard,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faHome,
  faSignInAlt,
  faSignOutAlt,
  faHistory,
  faBars,
  faUserPlus,
  faEnvelope,
  faInstagram,
  faFacebook,
  faSnapchat,
  faTwitter,
  faHandshake,
  faPlus,
  faTimes,
  faSearch,
  faHashtag,
  faShoppingBag,
  faStar,
  faStoreAlt,
  faArrowRight,
  faUserAlt,
  faUtensils,
  faConciergeBell,
  faHamburger,
  faWineBottle,
  faSpinner,
  faTrashAlt,
  faShoppingCart,
  faCreditCard,
);

export default library;
